{% set name = "hvsampledata" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hvsampledata-{{ version }}.tar.gz
  sha256: 3a45375c4e9982a2ce0b9ea18aa0f82954a20911ad8bd7065a3d9d9564b9701d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - platformdirs >=3.0.0
    - urllib3 >=1.26.0

test:
  imports:
    - hvsampledata
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/holoviz/hvsampledata
  summary: Datasets for the HoloViz projects
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Azaya89
    - hoxbro
    - maximlt
